# Generated by Django 4.2.5 on 2023-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_robot_model1_order_robot_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='robot_model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='robot_version',
        ),
        migrations.AddField(
            model_name='order',
            name='robot_serial',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
